### ISSUE TITLE
Generation Glitches after some time

### ISSUE THREAD

**Issue by OmegaRogue** [netblitzer/RealPlates#1]
This happens after running the simulation for a bit:
![image](https://user-images.githubusercontent.com/24958536/73140413-e88c8d80-4078-11ea-96b3-e3a208a49306.png)

**Comment by netblitzer** [comment]
Currently this project is in very early development. The problem you're seeing is because as of writing this, movement is extremely basic and was only implemented to ensure performance in the rendering code. This movement is not based in plate tectonics and will be scrapped soon.
